apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: spring-example
spec:
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: bharathoptdocker/my_spring_application:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: springboot-config
